name: Salvage
version: '${project.version}'
main: co.bitengine.salvage.Salvage
api-version: 1.13
authors: [ Denizen ]
description: Ultimate salvage plugin — create unlimited custom recipes to break items down into other items.
depend: [Menus]
commands:
  salvage:
    description: Root command for all salvage operations.
